return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  lazy = false,
  -- event = { 'BufReadPost', 'BufNewFile' },
  cmd = { 'TSUpdate', 'TSInstall', 'TSLog', 'TSUninstall' },
  opts = {
    indent = { enable = true },
    highlight = { enable = true },
    ensure_installed = {
      'bash',
      'c_sharp',
      'css',
      'diff',
      'gitignore',
      'go',
      'html',
      'javascript',
      'json',
      'lua',
      'luadoc',
      'luap',
      'markdown',
      'markdown_inline',
      'printf',
      'query',
      'regex',
      'typescript',
      'vue',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
    },
  },
}
