-- OmniSharp --
vim.keymap.set('n', '<leader>f', '<Cmd>OmniSharpFixUsings<CR><Cmd>OmniSharpCodeFormat<CR>')
vim.keymap.set('n', '<leader>r', '<Cmd>OmniSharpRename<CR>')
vim.keymap.set('n', '<C-k>', '<Cmd>OmniSharpSignatureHelp<CR>')
vim.keymap.set('i', '<C-k>', '<Cmd>OmniSharpSignatureHelp<CR>')
vim.keymap.set('n', '<leader>ca', '<Cmd>OmniSharpGetCodeActions<CR>')
vim.keymap.set('n', 'gd', '<Cmd>OmniSharpGotoDefinition<CR>')
vim.keymap.set('n', '<leader><C-r>', '<Cmd>!dotnet build<CR><Cmd>OmniSharpDebugProject<CR>')
vim.keymap.set('n', '<leader><C-u>', '<Cmd>OmniSharpDebugTest<CR>')
vim.keymap.set('n', '<leader><C-b>', '<Cmd>!dotnet build<CR>')
vim.keymap.set('n', '<leader><C-w>', '<Cmd>OmniSharpGlobalCodeCheck<CR>')
vim.keymap.set('n', '<leader>u', '<Cmd>OmniSharpFindUsages<CR>')
vim.keymap.set('n', '<leader>d', '<Cmd>OmniSharpDocumentation<CR>')
vim.keymap.set('n', '[[', '<Cmd>OmniSharpNavigateUp<CR>')
vim.keymap.set('n', ']]', '<Cmd>OmniSharpNavigateDown<CR>')
